language: ruby
sudo: false
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - jruby-18mode
  - jruby-19mode
  - ruby-head
  - jruby-head
  - ree
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
